### ISSUE TITLE
is there a plan to support dual SIM's phone?

### ISSUE THREAD

**Issue by magixbox** [youngj/EnvayaSMS#18]
It is kind of ironic that we can get dual SIM's android phones cheaper than the single SIM at this part of the planet.
I hope this is not too much to ask.

Forget about it if you have to move the mountain and the sea to achieve it...

**Comment by youngj** [comment]
As far as I can tell, Android does not currently have an API for interacting with multiple SIM cards, although device manufacturers may have SDKs for particular dual-sim phones:

http://stackoverflow.com/questions/5255147/dual-sim-card-android
http://stackoverflow.com/questions/7996197/detect-the-status-of-two-sim-cards-in-a-dual-sim-android-phone

What currently happens when you use EnvayaSMS in a dual SIM phone? Does it send/receive SMS from one or both phone numbers?

**Comment by magixbox** [comment]
EnvayaSMS sees only the "default" SIM, the one selected in the phone's settings.

I guess we can put this aside from now.
