### ISSUE TITLE
MMS security bug and Test bug

### ISSUE THREAD

**Issue by ChrisBdk** [youngj/EnvayaSMS#7]
First of all, THANKS fro the nice app, and the everything we need to use this nice app..

Well, when I send a MMS to my PHP server, I cant get pass the security check. 
It looks like it puts all the mms_part stuff, in the security calculater. 

And when I run a Test Connection, it sents a incomming action...

Keep it up, and let me know if I can do anything..

Cheers...

Bjørn

**Comment by youngj** [comment]
For your PHP server, are you using the included server library?
https://github.com/youngj/EnvayaSMS/blob/master/server/php/EnvayaSMS.php

The mms_parts field is included in the signature like any other POST field (before decoding the JSON)

Currently Test Connection is implemented by performing an 'outgoing' action and ignoring the results. That works for me because the 'outgoing' action doesn't change anything on my server... but I guess it should probably be changed to use its own action.

-Jesse

**Comment by ChrisBdk** [comment]
WOW..quick responce.. :)

Im running it right now on a MAMP server.. And yes, Im running it with your library...
But Let me try to re-install it.. :)

Well, I dont care if you change it, Im only going to use the incomming function.. But maybe change it, just to have it right.. :)

// Bjørn

**Comment by youngj** [comment]
The "test connection" button now uses the 'test' action in 2.0-beta7.

This may require updating the PHP server library:

https://github.com/youngj/EnvayaSMS/commit/03d5f556d75d7374798695bc389e3e742d0d602b#diff-0

**Comment by youngj** [comment]
is the security test for MMS messages working now?

**Comment by ChrisBdk** [comment]
Works.. :)
